"""Add tags

Revision ID: 6a8246654d0f
Revises: 7a3a46c08d21
Create Date: 2025-12-01 09:31:06.370908

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6a8246654d0f'
down_revision = '7a3a46c08d21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_index('idx_tags_user_name_lower', ['user_id', sa.literal_column('lower(`name`)')], unique=True)

    op.create_table('item_tags',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('item_id', 'tag_id')
    )
    with op.batch_alter_table('item_tags', schema=None) as batch_op:
        batch_op.create_index('idx_item_tags_tag_item', ['tag_id', 'item_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_uploads', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_11'), 'users', ['user_id'], ['id'], referent_schema='test')
        batch_op.create_index(batch_op.f('fk_10'), ['user_id'], unique=False)

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_2'), 'collections', ['collection_id'], ['id'], referent_schema='test')
        batch_op.create_foreign_key(batch_op.f('fk_1'), 'users', ['author_id'], ['id'], referent_schema='test')

    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_1'), 'users', ['user_id'], ['id'], referent_schema='test')

    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_3'), 'items', ['item_id'], ['id'], referent_schema='test')
        batch_op.create_foreign_key(batch_op.f('fk_2'), 'users', ['user_id'], ['id'], referent_schema='test')
        batch_op.create_index(batch_op.f('fk_1'), ['user_id'], unique=False)
        batch_op.alter_column('is_correct',
               existing_type=mysql.TINYINT(display_width=4),
               nullable=True)

    with op.batch_alter_table('item_tags', schema=None) as batch_op:
        batch_op.drop_index('idx_item_tags_tag_item')

    op.drop_table('item_tags')
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index('idx_tags_user_name_lower')

    op.drop_table('tags')
    # ### end Alembic commands ###
