"""add_type_to_collections

Revision ID: 7a3a46c08d21
Revises: ab81ff6e445c
Create Date: 2025-11-29 14:12:17.354250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a3a46c08d21'
down_revision = 'ab81ff6e445c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add type column with server default
    op.add_column('collections', sa.Column('type', sa.String(length=20), nullable=False, server_default='SUBJECT'))
    
    # Backfill existing collections (ensure all have SUBJECT type)
    op.execute("UPDATE collections SET type = 'SUBJECT' WHERE type IS NULL OR type = ''")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collections', 'type')
    # ### end Alembic commands ###
