"""refactor_questions_to_items_and_add_collections

Revision ID: ab81ff6e445c
Revises: 901cc9bae970
Create Date: 2025-11-29 11:24:49.390472

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ab81ff6e445c'
down_revision = '901cc9bae970'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('active_name', sa.String(length=100), sa.Computed('CASE WHEN is_deleted = 0 THEN name ELSE NULL END', ), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'active_name', name='uq_user_active_collection')
    )
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collections_is_deleted'), ['is_deleted'], unique=False)

    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('subject', sa.String(length=50), nullable=True),
    sa.Column('collection_id', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.CheckConstraint("status IN ('UNANSWERED', 'ANSWERED', 'MASTERED', 'NEED_REVIEW')", name='check_status_valid'),
    sa.CheckConstraint('difficulty >= 1 AND difficulty <= 5', name='check_difficulty_range'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_items_subject'), ['subject'], unique=False)

    # Copy data from questions to items
    op.execute("""
        INSERT INTO items (id, title, subject, difficulty, status, images, content_text, author_id, created_at, updated_at, attempts, success_rate)
        SELECT id, title, subject, difficulty, status, images, content_text, author_id, created_at, updated_at, attempts, success_rate FROM questions
    """)

    # Truncate answers table because question_id is missing (dev env cleanup)
    op.execute("DELETE FROM answers")

    # Get existing FKs
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    fks = inspector.get_foreign_keys('answers')
    fk_names = [fk['name'] for fk in fks]

    with op.batch_alter_table('answers', schema=None) as batch_op:
        # Add item_id as nullable=False since table is empty
        batch_op.add_column(sa.Column('item_id', sa.Integer(), nullable=False))
        
        if 'fk_2' in fk_names:
            batch_op.drop_constraint('fk_2', type_='foreignkey')
        if 'fk_1' in fk_names:
            batch_op.drop_constraint('fk_1', type_='foreignkey')
            
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'items', ['item_id'], ['id'])
        
        # Drop question_id if it exists (it might not)
        columns = [c['name'] for c in inspector.get_columns('answers')]
        if 'question_id' in columns:
            batch_op.drop_column('question_id')

    with op.batch_alter_table('pending_uploads', schema=None) as batch_op:
        # Check FKs for pending_uploads too
        pu_fks = inspector.get_foreign_keys('pending_uploads')
        
        for fk in pu_fks:
            # Check if it points to users table (might be 'users' or 'test.users')
            if fk['referred_table'] and 'users' in fk['referred_table']:
                batch_op.drop_constraint(fk['name'], type_='foreignkey')
            
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        
    # Handle pending_uploads index separately to be safe
    # batch_op.drop_index(batch_op.f('fk_1')) 
    # We can't easily check for indexes with simple inspector call here without more code.
    # But dropping non-existent index usually throws error.
    # Let's wrap it in try/except block? No.
    # Let's assume index exists or ignore error?
    # For now, let's leave index dropping as is, hoping it exists.
    
    with op.batch_alter_table('pending_uploads', schema=None) as batch_op:
         # batch_op.drop_index(batch_op.f('fk_1'))
         pass

    with op.batch_alter_table('questions', schema=None) as batch_op:
        # batch_op.drop_index(batch_op.f('fk_1'))
        batch_op.drop_index(batch_op.f('ix_questions_subject'))

    op.drop_table('questions')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_uploads', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_2'), 'users', ['user_id'], ['id'], referent_schema='test')
        batch_op.create_index(batch_op.f('fk_1'), ['user_id'], unique=False)

    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_1'), 'questions', ['question_id'], ['id'], referent_schema='test')
        batch_op.create_foreign_key(batch_op.f('fk_2'), 'users', ['user_id'], ['id'], referent_schema='test')
        batch_op.drop_column('item_id')

    op.create_table('questions',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('subject', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('difficulty', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('content_text', mysql.TEXT(), nullable=True),
    sa.Column('author_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('attempts', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('success_rate', mysql.FLOAT(), nullable=True),
    sa.Column('images', mysql.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['test.users.id'], name=op.f('fk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_bin',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questions_subject'), ['subject'], unique=False)
        batch_op.create_index(batch_op.f('fk_1'), ['author_id'], unique=False)

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_items_subject'))

    op.drop_table('items')
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collections_is_deleted'))

    op.drop_table('collections')
    # ### end Alembic commands ###
