"""Rename image_urls to images

Revision ID: ba2ec8abe6c1
Revises: 82b6799b95be
Create Date: 2025-11-23 16:55:58.587495

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'ba2ec8abe6c1'
down_revision = '82b6799b95be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('images', sa.JSON(), nullable=True))
        batch_op.drop_column('image_urls')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_urls', sqlite.JSON(), nullable=True))
        batch_op.drop_column('images')

    # ### end Alembic commands ###
