"""Add pending_uploads table

Revision ID: be1ada0e0439
Revises: ba2ec8abe6c1
Create Date: 2025-11-24 17:33:07.749417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be1ada0e0439'
down_revision = 'ba2ec8abe6c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_uploads',
    sa.Column('public_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('public_id')
    )
    # Add indexes for performance
    op.create_index('idx_pending_uploads_user_id', 'pending_uploads', ['user_id'])
    op.create_index('idx_pending_uploads_created_at', 'pending_uploads', ['created_at'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_pending_uploads_created_at', 'pending_uploads')
    op.drop_index('idx_pending_uploads_user_id', 'pending_uploads')
    op.drop_table('pending_uploads')
    # ### end Alembic commands ###
